#Springboot-jdk-17
name: main-workflow
on: 
  workflow_dispatch
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    outputs:
      file1: ${{ steps.pub.outputs.test}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: echo
        run: |
          ls -la
          echo "passed"
      - name: GitGuardian Shield Action
  # You may pin to the exact commit or the version.
  # uses: GitGuardian/ggshield-action@4848e499be8c740d2d71526182c1343d577d7322
        run: |
          pip install ggshield
          ggshield auth ${{ secrets.GITGUARDIAN_API_TOKEN }}
          ggshield secret scan path ./
          
      - id: pub
        run: echo "test=hello-world" >> $GITHUB_OUTPUT
      - name: output
        run: echo "${{ toJSON(github) }}"
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: package
        run: mvn clean package
      - name: file check
        run: ls -la target
      - name: unit-test
        run: | 
          mvn test
          ls -la
          ls -la target
          cd target
          cd site
          ls -la jacoco
      - name: Publish Test Results
  # You may pin to the exact commit or the version.
  # uses: EnricoMi/publish-unit-test-result-action@ca89ad036b5fcd524c1017287fb01b5139908408
        uses: EnricoMi/publish-unit-test-result-action@v2.11.0
        with:
          comment_mode: off
          files: | 
            target/surefire-reports/TEST-*.xml
        
    #  - name: JaCoCo Report
    #    uses: Madrapps/jacoco-report@v1.6.1
    #    with:
    #      paths: target/site/jacoco/jacoco.xml
    #      token: ${{secrets.TOKEN_REPO}}
    #      min-coverage-overall: 60
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: info
        run: echo ${{needs.build.outputs.file1}}
      - name: display
        id: show
        run: echo "speed=fast"  >> $GITHUB_OUTPUT
      - name: out
        run: echo ${{steps.show.outputs.speed}}
      - name: checking
        run: ls -la
