name: main-workflow
on:
  workflow_dispatch
jobs:
  build:
    runs-on: self
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: echo
        run: |
          ls -la
          echo "passed"
      - name: output
        run: echo "${{ toJSON(github) }}
     
