name: main-workflow
on:
  workflow_dispatch
jobs:
  build:
    runs-on: self
    outputs:
      file1: ${{ steps.pub.outputs.test}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: echo
        run: |
          ls -la
          echo "passed"
      - id: pub
        run: echo "test=hello-world" >> $GITHUB_OUTPUT
      - name: output
        run: echo "${{ toJSON(github) }}"
      - name: Installing JDK
        run: |
          if [ $(java --version) == exit 0]; then
          echo "jdk is installed"
          else
          apt install openjdk-17-jdk openjdk-17-jre -y
          fi
      - name: installing maven
        run: |
          if [ $(mvn version) == exit 0]; then
          echo "maven installed"
          else
          apt install maven -y
          fi
      - name: package
        run: mvn clean package
  test:
    runs-on: self
    needs: build
    steps:
      - name: info
        run: echo ${{needs.build.outputs.file1}}
      - name: display
        id: show
        run: echo "speed=fast"  >> $GITHUB_OUTPUT
      - name: out
        run: echo ${{steps.show.outputs.speed}}
