name: main-workflow
on:
  workflow_dispatch
jobs:
  build:
    runs-on: self
    container: node:16
    steps:
      - name: checking version
        run: docker version
      - name: echo
        run: echo "passed"
     
